spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/AuctionApp
    username:  ${username}
    password: ${password}
server:
  port: 8080
secret:
  jwt:  ${secret}
expiration:
  jwt:  ${expiration}
stripe:
  sk_key: ${stripe_sk}
